import type {
  AgentSettings, ChatMessage, MCPServerConfig, PendingApproval, PreviewFile,
  Project, RenderBlock, RenderBlockSeries, SessionSummary, SessionUsage,
  SkillConfig, ToolUnit,
} from "./types";
import type { PendingQuestion } from "./components/QuestionModal";
import type { RemoteHostDto, RemotePairDto } from "../api";
import type {
  ChoiceOption, ConfirmState, PendingAttachment, Review, SearchHit,
  StoredAttachment, TodoItem, TurnActivity, WorkspaceStatus,
} from "./viewTypes";

/** Contexto de vista partilhado pelos componentes de layout (sidebar, transcript, composer, onboarding, modais).
 * Gerado por scripts/rc_viewctx.py a partir dos símbolos reais da página. */
export interface RemoteCodeViewCtx {
  accessBtn: HTMLButtonElement | undefined;
  accessMenuOpen: () => boolean;
  activeContext: () => any;
  activeHost: () => any;
  activeHostId: () => string;
  activeModel: () => string;
  activeProject: () => any;
  activeSession: () => SessionSummary | null;
  activeSessionId: () => string;
  activeUsage: () => SessionUsage | null;
  addBtn: HTMLButtonElement | undefined;
  addContextOpen: () => boolean;
  agentMode: () => string;
  answerQuestion: (answers: string[][]) => any;
  appNotice: () => { message: string; kind: "ok" | "err" } | null;
  blockRawIdx: (block: RenderBlock) => number;
  cancelCurrentTurn: () => any;
  cancelEditMsg: () => any;
  cancelSettings: () => any;
  cancelTurnForSession: (sessionId: string, e?: MouseEvent | KeyboardEvent) => any;
  checkWorkspace: () => any;
  choiceState: () => { title: string; message: string; options: ChoiceOption[]; resolve: (id: string | null) => void } | null;
  closeMenus: () => any;
  closeSidebarOnMobile: () => any;
  configureSession: () => any;
  confirmState: () => ConfirmState | null;
  connectionState: () => "connecting" | "connected" | "disconnected";
  contextBtn: HTMLButtonElement | undefined;
  convWidth: () => "narrow" | "default" | "wide";
  convWidthClass: () => any;
  copiedMsgId: () => string | null;
  copyMsg: (id: string, text: string) => any;
  createProject: () => any;
  creatingSession: () => boolean;
  currentProject: () => any;
  daemonSettings: () => AgentSettings;
  deleteMsg: (idx: number) => Promise<any>;
  deleteProject: (id: string, e: MouseEvent) => Promise<any>;
  deleteSelected: () => Promise<any>;
  deleteSession: (id: string, e?: MouseEvent) => Promise<any>;
  downloadPreviewFile: () => any;
  draftMode: () => boolean;
  editingMsgIdx: () => number | null;
  editingMsgText: () => string;
  effort: () => string;
  elapsedLabel: (ms: number) => string;
  exitSelectionMode: () => any;
  expandedThinking: () => Record<string, boolean>;
  filesBtn: HTMLButtonElement | undefined;
  filesMenuOpen: () => boolean;
  folderCurrent: () => string;
  folderEntries: () => { name: string; path: string }[];
  folderError: () => string;
  folderLoading: () => boolean;
  folderParent: () => string;
  forkMessage: (block: RenderBlock) => any;
  forking: () => boolean;
  generatePairingToken: () => Promise<any>;
  growWindow: () => any;
  handleAddMcpServer: () => any;
  handleAddSkill: () => any;
  handleDeleteMcpServer: (name: string) => any;
  handleDeleteSkill: (name: string) => any;
  handleFiles: (files: FileList | File[]) => Promise<any>;
  hiddenCount: () => any;
  historyView: () => boolean;
  hostBtn: HTMLButtonElement | undefined;
  hostMenuOpen: () => boolean;
  hosts: () => RemoteHostDto[];
  inputPrompt: () => string;
  isAtBottom: () => boolean;
  isMobile: () => any;
  isProjectExpanded: (p: { id: string }) => any;
  keepChanges: () => any;
  loadHosts: () => Promise<any>;
  looseSessions: () => any;
  matchQuery: (s: SessionSummary) => boolean;
  mcpServers: () => Record<string, MCPServerConfig>;
  messages: () => ChatMessage[];
  modeBtn: HTMLButtonElement | undefined;
  modeMenuOpen: () => boolean;
  modelBtn: HTMLButtonElement | undefined;
  modelMenuOpen: () => boolean;
  modelPickerBody: () => any;
  newMcpArgs: () => string;
  newMcpCmd: () => string;
  newMcpName: () => string;
  newMcpTransport: () => string;
  newMcpUrl: () => string;
  newProjBtn: HTMLButtonElement | undefined;
  newProjectMenuOpen: () => boolean;
  newProjectPath: () => string;
  newSkillBody: () => string;
  newSkillDesc: () => string;
  newSkillName: () => string;
  onChatScroll: () => any;
  openNewProjectModal: () => any;
  openSettings: (sectionId?: string) => any;
  openStoredPreview: (sessionId: string, attachmentId: string) => any;
  pairingData: () => RemotePairDto | null;
  pairingLoading: () => boolean;
  pendingApproval: () => PendingApproval | null;
  pendingAttachments: () => PendingAttachment[];
  pendingQuestion: () => PendingQuestion | null;
  pickProject: (id: string) => any;
  pickSlash: (cmd: string) => any;
  pinSelected: () => Promise<any>;
  previewCopied: () => boolean;
  previewFile: () => PreviewFile | null;
  previewPending: (a: { name: string; mime: string; text?: string; objectUrl?: string; dataB64?: string; size?: number }) => void;
  projBtn: HTMLButtonElement | undefined;
  projectMenuOpen: () => boolean;
  projectSessions: (projectId: string) => SessionSummary[];
  projects: () => Project[];
  questionError: () => string;
  questionSubmitting: () => boolean;
  queueDaemonSearch: (q: string) => any;
  quickStartProject: () => any;
  rawIdx: (idx: number) => number;
  regenerateMsg: (idx: number) => Promise<any>;
  removeHost: () => Promise<any>;
  removePendingAttachment: (key: string) => any;
  renameText: () => string;
  renamingId: () => string | null;
  renderBlocks: () => RenderBlock[];
  requestFolders: (path: string) => any;
  requestReview: (detail?: boolean, background?: boolean) => any;
  respondApproval: (approved: boolean, always?: boolean) => any;
  restorePreviewFile: () => any;
  reviewError: () => string;
  reviewLoading: () => boolean;
  reviewOpen: () => boolean;
  saveDaemonConfig: () => any;
  saveEditMsg: (idx: number, m: ChatMessage) => Promise<any>;
  scrollToBottom: (force?: boolean) => any;
  searchResults: () => SearchHit[];
  selectSession: (id: string) => any;
  selectedSessions: () => Set<string>;
  selectedSkills: () => string[];
  selectionMode: () => boolean;
  sendPrompt: () => Promise<any>;
  sessionFiles: () => Record<string, StoredAttachment[]>;
  sessionFilter: () => string;
  sessionListToggle: (key: string, count: number) => any;
  sessionStatus: () => "idle" | "running";
  sessions: () => SessionSummary[];
  setAccessMenuOpen: (v: boolean | ((p: boolean) => boolean)) => void;
  setActiveHostId: (v: string | ((p: string) => string)) => void;
  setAddContextOpen: (v: boolean | ((p: boolean) => boolean)) => void;
  setAgentMode: (v: string | ((p: string) => string)) => void;
  setAppNotice: (v: { message: string; kind: "ok" | "err" } | null | ((p: { message: string; kind: "ok" | "err" } | null) => { message: string; kind: "ok" | "err" } | null)) => void;
  setChatContainerRef: (v: HTMLDivElement | null | ((p: HTMLDivElement | null) => HTMLDivElement | null)) => void;
  setChatContentRef: (v: HTMLDivElement | null | ((p: HTMLDivElement | null) => HTMLDivElement | null)) => void;
  setConfirmState: (v: ConfirmState | null | ((p: ConfirmState | null) => ConfirmState | null)) => void;
  setConvWidth: (v: "narrow" | "default" | "wide" | ((p: "narrow" | "default" | "wide") => "narrow" | "default" | "wide")) => void;
  setDaemonSettings: (v: AgentSettings | ((p: AgentSettings) => AgentSettings)) => void;
  setEditingMsgText: (v: string | ((p: string) => string)) => void;
  setExpandedThinking: (v: Record<string, boolean> | ((p: Record<string, boolean>) => Record<string, boolean>)) => void;
  setFilesMenuOpen: (v: boolean | ((p: boolean) => boolean)) => void;
  setHistoryView: (v: boolean | ((p: boolean) => boolean)) => void;
  setHostMenuOpen: (v: boolean | ((p: boolean) => boolean)) => void;
  setInputPrompt: (v: string | ((p: string) => string)) => void;
  setIsAtBottom: (v: boolean | ((p: boolean) => boolean)) => void;
  setModeMenuOpen: (v: boolean | ((p: boolean) => boolean)) => void;
  setModelMenuOpen: (v: boolean | ((p: boolean) => boolean)) => void;
  setNewMcpArgs: (v: string | ((p: string) => string)) => void;
  setNewMcpCmd: (v: string | ((p: string) => string)) => void;
  setNewMcpName: (v: string | ((p: string) => string)) => void;
  setNewMcpTransport: (v: string | ((p: string) => string)) => void;
  setNewMcpUrl: (v: string | ((p: string) => string)) => void;
  setNewProjectMenuOpen: (v: boolean | ((p: boolean) => boolean)) => void;
  setNewProjectPath: (v: string | ((p: string) => string)) => void;
  setNewSkillBody: (v: string | ((p: string) => string)) => void;
  setNewSkillDesc: (v: string | ((p: string) => string)) => void;
  setNewSkillName: (v: string | ((p: string) => string)) => void;
  setPreviewCopied: (v: boolean | ((p: boolean) => boolean)) => void;
  setPreviewFile: (v: PreviewFile | null | ((p: PreviewFile | null) => PreviewFile | null)) => void;
  setProjectMenuOpen: (v: boolean | ((p: boolean) => boolean)) => void;
  setRenameText: (v: string | ((p: string) => string)) => void;
  setRenamingId: (v: string | null | ((p: string | null) => string | null)) => void;
  setReviewOpen: (v: boolean | ((p: boolean) => boolean)) => void;
  setSearchResults: (v: SearchHit[] | ((p: SearchHit[]) => SearchHit[])) => void;
  setSelectedSkills: (v: string[] | ((p: string[]) => string[])) => void;
  setSelectionMode: (v: boolean | ((p: boolean) => boolean)) => void;
  setSessionFilter: (v: string | ((p: string) => string)) => void;
  setShowConfigModal: (v: boolean | ((p: boolean) => boolean)) => void;
  setShowNewProjectModal: (v: boolean | ((p: boolean) => boolean)) => void;
  setShowPairModal: (v: boolean | ((p: boolean) => boolean)) => void;
  setShowTruncateInput: (v: boolean | ((p: boolean) => boolean)) => void;
  setSidebarOpen: (v: boolean | ((p: boolean) => boolean)) => void;
  setSlashIndex: (v: number | ((p: number) => number)) => void;
  setTodosOpen: (v: boolean | ((p: boolean) => boolean)) => void;
  setTruncateTokens: (v: number | ((p: number) => number)) => void;
  setUsageOpen: (v: boolean | ((p: boolean) => boolean)) => void;
  setVerboseChat: (v: any) => void;
  setYoloMode: (v: boolean | ((p: boolean) => boolean)) => void;
  showConfigModal: () => boolean;
  showNewProjectModal: () => boolean;
  showPairModal: () => boolean;
  showTruncateInput: () => boolean;
  sidebarOpen: () => boolean;
  skills: () => Record<string, SkillConfig>;
  slashIndex: () => number;
  slashMatches: () => any;
  sortedSessions: (list: SessionSummary[]) => SessionSummary[];
  specialProgress: (units: ToolUnit[]) => string | undefined;
  startEditMsg: (idx: number, m: ChatMessage) => any;
  startNewConversation: (projectId?: string) => any;
  submitRename: (id: string) => any;
  taskReview: () => Review | null;
  thinkingElapsed: () => number;
  thinkingIndex: () => number;
  thinkingStart: () => number | null;
  timeAgo: (ts: number) => any;
  toast: (message: string, kind?: "ok" | "err") => any;
  todos: () => TodoItem[];
  todosOpen: () => boolean;
  togglePin: (id: string, e: MouseEvent) => any;
  toggleProjectExpanded: (id: string) => any;
  toggleSessionSelect: (id: string) => any;
  toggleSkill: (name: string) => any;
  toggleToolGroup: (key: string) => any;
  toggleToolOpen: (key: string) => any;
  toolGroupOpen: () => Record<string, boolean>;
  toolOpen: () => Record<string, boolean>;
  toolProgress: () => Record<string, string>;
  toolStarts: () => Record<string, number>;
  transcriptScroll: { schedule: (force?: boolean) => void; measure: () => void; detach: () => void; reset: () => void; dispose: () => void };
  truncatePreviewFile: () => any;
  truncateTokens: () => number;
  turnActivity: () => TurnActivity | null;
  turnClock: () => number;
  turnLabel: () => any;
  undoChanges: (path?: string) => Promise<any>;
  usageOpen: () => boolean;
  verboseChat: () => boolean;
  visibleBlocks: () => RenderBlock[];
  visibleSessions: (key: string, list: SessionSummary[]) => SessionSummary[];
  workspace: () => WorkspaceStatus | null;
  workspaceBlocked: () => any;
  workspacePath: () => any;
  workspaceState: () => any;
  wsOpen: () => boolean;
  yoloMode: () => boolean;
}
