package tools

import (
	"context"
	"errors"
	"io"
	"os"
	"os/exec"
	"strings"
	"time"
)

// errEmptyArgv is the direct starter's guard against a malformed spec.
var errEmptyArgv = errors.New("tools: empty argv")

// ExecSpec is everything needed to run one command (owner: terminal AND
// python go through the same runner — it never knows what it runs).
type ExecSpec struct {
	Kind     string   // "bash" | "python"
	Command  string   // original command text (labels, sandbox already checked)
	Argv     []string // binary + args (exec semantics)
	CWD      string
	Env      []string
	Stdin    string // inline stdin (python's -c payload)
	// SplitStderr keeps a separate stderr log (python's legacy shape);
	// the runner merges both into one out log and leaves this false.
	SplitStderr bool
	LogDir   string // direct-starter temp log directory
	JobID    string // runner identity (pre-generated by the daemon side)
	SessionID string
	Label    string
}

// Proc is the tool-visible handle of one running command.
type Proc struct {
	PID     int
	LogPath string // live log file (tailable)
	// JobID is the runner-assigned identity ("" = let the background
	// registry generate one at registration, legacy direct path).
	JobID string
	// ErrLogPath is the separate stderr log (SplitStderr; "" = merged).
	ErrLogPath string
	// BrainLog is the final log destination (runner copies there at
	// terminal; == LogPath for the direct path).
	BrainLog string
	Exited   <-chan struct{}
	Wait     func() error                        // blocks until the process is gone
	Stop     func()                              // kill the whole tree
	Pump     func(<-chan struct{}, func([]byte)) // tails the log into consume
	PumpErr  func(<-chan struct{}, func([]byte)) // separate stderr log (nil = merged)
	Cleanup  func(removeLog bool)
	// Disposition records the execution disposition durably (V2R-001).
	// Nil on the direct path.
	Disposition Disposition
}

// Starter launches a command. Nil on the tools = the direct local
// starter (tests/standalone). The daemon injects the runner-backed
// starter (crash-only tasks: state file + runners/out/ + IPC).
type Starter func(ctx context.Context, spec ExecSpec) (*Proc, error)

// Disposition records how a task's outcome is consumed (V2R-001) so a
// restart never invents a wake-up. Nil = no-op (direct path). Best-effort.
type Disposition func(jobID, disp string)

// Disposition values (mirror packages/runner).
const (
	DispBackground = "background"
	DispInline     = "inline"
	DispSuppressed = "suppressed"
)

// startDirect is today's behavior: a local process whose output lands in
// a temp file under LogDir; the pump only observes the file (killing the
// daemon can never SIGPIPE the child).
func startDirect(ctx context.Context, spec ExecSpec) (*Proc, error) {
	if len(spec.Argv) == 0 {
		return nil, errEmptyArgv
	}
	log, err := newProcessLog(spec.LogDir, "bg_"+spec.Kind+"_*.log")
	if err != nil {
		return nil, err
	}
	cmd := exec.CommandContext(ctx, spec.Argv[0], spec.Argv[1:]...)
	cmd.Dir = spec.CWD
	cmd.Env = spec.Env
	if spec.Stdin != "" {
		cmd.Stdin = strings.NewReader(spec.Stdin)
	}
	setProcessGroup(cmd)
	cmd.Stdout = log.file
	var errLog *processLog
	if spec.SplitStderr {
		if errLog, err = newProcessLog(spec.LogDir, "bg_"+spec.Kind+"_stderr_*.log"); err != nil {
			log.close(true)
			return nil, err
		}
		cmd.Stderr = errLog.file
	} else {
		cmd.Stderr = log.file
	}
	if err := cmd.Start(); err != nil {
		log.close(true)
		if errLog != nil {
			errLog.close(true)
		}
		return nil, err
	}
	exited := make(chan struct{})
	var waitErr error
	go func() {
		waitErr = cmd.Wait() // reaped ONCE: cmd.Wait() must never be
		close(exited)        // called twice ("Wait was already called")
	}()
	proc := &Proc{
		PID:      cmd.Process.Pid,
		LogPath:  log.file.Name(),
		BrainLog: log.file.Name(),
		Exited:   exited,
		Wait: func() error {
			<-exited
			return waitErr // safe: exited closes after the write
		},
		Stop:    func() { killProcessGroup(cmd) },
		Pump:    log.pump,
		Cleanup: log.close,
	}
	if errLog != nil {
		proc.ErrLogPath = errLog.file.Name()
		proc.PumpErr = errLog.pump
		proc.Cleanup = func(remove bool) { log.close(remove); errLog.close(remove) }
	}
	return proc, nil
}

// startWith launches through the injected starter or the direct one.
func startWith(ctx context.Context, st Starter, spec ExecSpec) (*Proc, error) {
	if st != nil {
		return st(ctx, spec)
	}
	return startDirect(ctx, spec)
}

// TailLog observes an EXISTING log file (the runner's out file) exactly
// like processLog.pump does for a file this process owns.
func TailLog(path string) func(<-chan struct{}, func([]byte)) {
	return func(exited <-chan struct{}, consume func([]byte)) {
		// The runner creates its out file shortly AFTER spawn (its own
		// boot): wait for the file to appear — the file is the contract,
		// so the tailer is late-arrival tolerant and bounded.
		var f *os.File
		deadline := time.Now().Add(15 * time.Second)
		for {
			var err error
			f, err = os.Open(path)
			if err == nil {
				break
			}
			if time.Now().After(deadline) {
				return
			}
			select {
			case <-exited:
				// One last attempt after exit (the file exists by then).
				if f2, err2 := os.Open(path); err2 == nil {
					f = f2
					goto opened
				}
				return
			case <-time.After(20 * time.Millisecond):
			}
		}
	opened:
		defer f.Close()
		tick := time.NewTicker(20 * time.Millisecond)
		defer tick.Stop()
		buf := make([]byte, 8192)
		var offset int64
		ending := false
		for {
			n, err := f.ReadAt(buf, offset)
			if n > 0 {
				consume(buf[:n])
				offset += int64(n)
			}
			if err != nil && err != io.EOF {
				return
			}
			if n > 0 {
				continue
			}
			if ending {
				return
			}
			select {
			case <-exited:
				ending = true
			case <-tick.C:
			}
		}
	}
}
